spring.application.name=ban-wine-express
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=urban_wine_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=sa123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Access token: 15 phut (900000 ms)
jwt.expiration-ms=900000
# Refresh token: 7 ngay (604800000 ms)
jwt.refresh-expiration-ms=604800000

# =========================================================
# CẤU HÌNH GỬI EMAIL THẬT QUA GMAIL SMTP
# =========================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Vnguyenthanh0805@gmail.com
spring.mail.password=oxzytsuokeaucuix
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# =========================================================
# CẤU HÌNH CỔNG THANH TOÁN VNPAY GATEWAY (SANDBOX)
# =========================================================
vnpay.tmn-code=75FFOF52
vnpay.hash-secret=XJELTYRGBOSFGEHTLKTJVNJSNUSJOCGD
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/payment/vnpay-return